import { Component, computed, effect, inject, input, output, signal, untracked } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Catalogue, Colour, Size, SizeType, VariantRow } from '../../core/catalogue';
import { formatMoney, parseAmount } from '../../core/money';

interface ColourGroup {
  colour: VariantRow['color'];
  rows: VariantRow[];
}

// The grid that creates every SKU of a design at once: tick the colours, tick the
// sizes, give a price, and each combination becomes a variant with its own SKU and
// barcode (generated by the database, so they can never collide).
@Component({
  selector: 'app-variant-manager',
  imports: [RouterLink],
  templateUrl: './variant-manager.html',
  styleUrl: './variant-manager.scss',
})
export class VariantManager {
  private readonly catalogue = inject(Catalogue);

  readonly productId = input.required<number>();
  readonly sizeType = input.required<SizeType>();
  readonly colours = input.required<Colour[]>();
  readonly sizes = input.required<Size[]>();
  readonly variantsChange = output<VariantRow[]>();

  protected readonly variants = signal<VariantRow[]>([]);
  protected readonly loaded = signal(false);
  protected readonly busy = signal(false);
  protected readonly message = signal<{ kind: 'ok' | 'error'; text: string } | null>(null);

  protected readonly pickedColours = signal<ReadonlySet<number>>(new Set());
  protected readonly pickedSizes = signal<ReadonlySet<number>>(new Set());
  protected readonly showAllSizes = signal(false);
  protected readonly newPrice = signal('');
  protected readonly allPrice = signal('');

  protected readonly offeredColours = computed(() => this.colours().filter((c) => c.active));
  protected readonly offeredSizes = computed(() =>
    this.sizes().filter((s) => s.active && (this.showAllSizes() || s.size_type === this.sizeType())),
  );

  private readonly existing = computed(() => new Set(this.variants().map((v) => `${v.color_id}-${v.size_id}`)));

  /** Combinations ticked that don't exist yet. */
  protected readonly toAdd = computed(() => {
    const combos: { color_id: number; size_id: number }[] = [];
    for (const color_id of this.pickedColours()) {
      for (const size_id of this.pickedSizes()) {
        if (!this.existing().has(`${color_id}-${size_id}`)) combos.push({ color_id, size_id });
      }
    }
    return combos;
  });

  protected readonly groups = computed<ColourGroup[]>(() => {
    const byColour = new Map<number, ColourGroup>();
    for (const v of this.variants()) {
      const group = byColour.get(v.color_id) ?? { colour: v.color, rows: [] };
      group.rows.push(v);
      byColour.set(v.color_id, group);
    }
    return [...byColour.values()];
  });

  constructor() {
    // Reload whenever the design changes (including the first time it is known).
    effect(() => {
      const id = this.productId();
      this.loaded.set(false);
      untracked(() => this.reload(id));
    });
  }

  protected toggleColour(id: number): void {
    this.pickedColours.update((s) => toggled(s, id));
  }

  protected toggleSize(id: number): void {
    this.pickedSizes.update((s) => toggled(s, id));
  }

  protected isTaken(sizeId: number): boolean {
    // A size is "taken" only if every ticked colour already has it.
    const colours = this.pickedColours();
    return colours.size > 0 && [...colours].every((c) => this.existing().has(`${c}-${sizeId}`));
  }

  protected async add(): Promise<void> {
    const price = parseAmount(this.newPrice());
    if (price === null || price <= 0) {
      this.message.set({ kind: 'error', text: 'Enter a price in euros first, for example 29.90.' });
      return;
    }
    const combos = this.toAdd();
    if (!combos.length || this.busy()) return;

    await this.run(async () => {
      await this.catalogue.addVariants(this.productId(), combos, price);
      this.pickedSizes.set(new Set());
      await this.reload(this.productId());
      return `Added ${combos.length} ${combos.length === 1 ? 'size' : 'sizes'}.`;
    });
  }

  protected async savePrice(v: VariantRow, text: string): Promise<void> {
    const price = parseAmount(text);
    if (price === null) {
      this.message.set({ kind: 'error', text: 'That isn’t a price. Use numbers only, for example 29.90.' });
      await this.reload(this.productId()); // put the old value back on screen
      return;
    }
    if (price === Number(v.price_eur)) return;
    await this.run(async () => {
      await this.catalogue.updateVariant(v.id, { price_eur: price });
      this.patch(v.id, { price_eur: price });
      return null;
    });
  }

  protected async setAll(): Promise<void> {
    const price = parseAmount(this.allPrice());
    if (price === null || price <= 0) {
      this.message.set({ kind: 'error', text: 'Enter the price to give every size, for example 29.90.' });
      return;
    }
    await this.run(async () => {
      await this.catalogue.setAllPrices(this.productId(), price);
      this.allPrice.set('');
      await this.reload(this.productId());
      return `Every size is now ${formatMoney(price, 'EUR')}.`;
    });
  }

  protected async setActive(v: VariantRow, active: boolean): Promise<void> {
    await this.run(async () => {
      await this.catalogue.updateVariant(v.id, { active });
      this.patch(v.id, { active });
      return null;
    });
  }

  protected async remove(v: VariantRow): Promise<void> {
    if (!confirm(`Remove ${v.color.name} ${v.size.label} (${v.sku})? This can’t be undone.`)) return;
    await this.run(async () => {
      await this.catalogue.deleteVariant(v.id);
      await this.reload(this.productId());
      return `Removed ${v.sku}.`;
    });
  }

  protected money(amount: number): string {
    return formatMoney(Number(amount), 'EUR');
  }

  protected margin(v: VariantRow): number | null {
    const price = Number(v.price_eur);
    const cost = Number(v.cost_eur);
    return cost > 0 && price > 0 ? Math.round(((price - cost) / price) * 100) : null;
  }

  protected units(v: VariantRow): number {
    return v.stock?.qty_physical ?? 0;
  }

  private patch(id: number, change: Partial<VariantRow>): void {
    this.variants.update((all) => all.map((v) => (v.id === id ? { ...v, ...change } : v)));
    this.variantsChange.emit(this.variants());
  }

  private async reload(id: number): Promise<void> {
    try {
      const rows = await this.catalogue.listVariants(id);
      this.variants.set(rows);
      this.variantsChange.emit(rows);
      // Suggest the price already used, so adding a size doesn't mean retyping it.
      if (!this.newPrice() && rows.length) this.newPrice.set(String(rows[0].price_eur));
    } catch (e) {
      this.message.set({ kind: 'error', text: (e as Error).message });
    } finally {
      this.loaded.set(true);
    }
  }

  private async run(action: () => Promise<string | null>): Promise<void> {
    this.busy.set(true);
    this.message.set(null);
    try {
      const done = await action();
      if (done) this.message.set({ kind: 'ok', text: done });
    } catch (e) {
      this.message.set({ kind: 'error', text: (e as Error).message });
      await this.reload(this.productId());
    } finally {
      this.busy.set(false);
    }
  }
}

function toggled(set: ReadonlySet<number>, id: number): ReadonlySet<number> {
  const next = new Set(set);
  if (!next.delete(id)) next.add(id);
  return next;
}
